### ISSUE TITLE
Lag, or it's cousin, wireless lag.

### ISSUE THREAD

**Issue by FreezePhoenix** [NexusNull/ALBot#20]
It appears that the bot is taking longer to login on some platforms - wondering if you had any clue what this could be, or not. In addition, they seem to have instants where they just stand there.

**Comment by FreezePhoenix** [comment]
ping jumps up to thousands of MS, entities do not seem to be updated, and... in general they just die.

**Comment by FreezePhoenix** [comment]
Just earlier this day, I saw a ping of 7 seconds...

It also seems to log that it is pulling entities _very_ often.

Code cost somehow rises up to  insane amounts, nearing 80% of the limit.

**Comment by FreezePhoenix** [comment]
![image](https://user-images.githubusercontent.com/24441367/55423509-0b7b0d80-554c-11e9-9f03-5ba2ed7d149b.png)
I don't know why this is happening, hoping you might know.

https://nebulous-albot.glitch.me/

I'm not on a PVP server, and they usually were able to handle boars - I just have no clue why they are starting to fail now.

**Comment by NexusNull** [comment]
1) Slow login might be caused by it loading data.js for every character. If you already have a slow connection that isn't going to make it any faster. I might implement a more efficient version of the current system in the future.

2) "It also seems to log that it is pulling entities very often." Well if you get out of sync that is what the game will do.

3) If your connection hangs and you send a many messages at the same time your code cost will definitely rise.

Generally I think the issue here is a slow and unstable connection. I never heard of a similar problem before.

**Comment by FreezePhoenix** [comment]
Yeah, slow connection would probably be it... and it probably doesn't help that i'm not using the mainstream Repo.
